### ISSUE TITLE
Add a feed?

### ISSUE THREAD

**Issue by tfausak** [nmattia/nmattia.com#1]
I would like to be able to follow an RSS or Atom feed of your posts. Hakyll supports this out of the box: https://jaspervdj.be/hakyll/tutorials/05-snapshots-feeds.html

**Comment by nmattia** [comment]
@tfausak good idea, thanks for the link. I'll try to add that asap.

**Comment by nmattia** [comment]
Ok, I _think_ I've implemented it. To be honest I've never used either RSS or Atom. @tfausak could you check [here](http://www.nmattia.com) and let me know if it works for you?

**Comment by tfausak** [comment]
:tada: That worked great! I was able to get the feed at http://www.nmattia.com/atom.xml. 

If you're feeling extra nice, would you mind adding a `<link rel="alternate" ...>` pointing to the feed? That makes it a lot easier to find. http://stackoverflow.com/questions/440391/how-to-tell-web-browsers-about-atom-feeds

**Comment by nmattia** [comment]
Ah ha! I installed an extension earlier and was disappointed not to see it light up when I got on the page. It does, now! Thanks :) Feel free to close if it works for you as well.
