### ISSUE TITLE
Update "index" title

### ISSUE THREAD

**Issue by peterpeterparker** [nmattia/nmattia.com#13]
Google reference your website main page as "Nicolas Mattia – index", probably would be cooler to reference it as "Nicolas Mattia"

Not sure if and how it should be modified in [default.html](https://github.com/nmattia/nmattia.com/blob/2c23d959fd6d2fe6fc250849d44ec1a8d7397fc0/templates/default.html#L11) or where you call it with the value "index"

Notabene: once updated and live, the Google cache need to be refreshed

<img width="1019" alt="Capture d’écran 2019-07-08 à 18 00 27" src="https://user-images.githubusercontent.com/16886711/60824810-96eae700-a1aa-11e9-808c-3b8a62077587.png">

**Comment by nmattia** [comment]
Good call! Implemented: https://github.com/nmattia/nmattia.com/commit/a5ad2d6f6c268d2ff150b55618cc1a0b40b25c8f
