### ISSUE TITLE
OG meta tags

### ISSUE THREAD

**Issue by peterpeterparker** [nmattia/nmattia.com#6]
No OG meta tags are declared/defined in the header of your website pages (http://ogp.me)

Long story short, og meta tags were introduce by Facebook but are now kind of use by every social network (like twitter) to generate a preview (= card) of the content you would share

Useful specially when you would share your blog posts, therefore the tags should be dynamic aka relative of the page where they are declared

**Comment by nmattia** [comment]
Done! :tada:
