### ISSUE TITLE
Slides for An Overview of Language Support in Nix

### ISSUE THREAD

**Issue by jtojnar** [nmattia/nmattia.com#76]
Hi, thanks for the presentation, it was one of the best on the conference.

https://www.nmattia.com/posts/2019-11-12-language-support-overview-nixcon.html 

Do you still have slides for it somewhere?

I am linking the YouTube video from my [new tool for PHP](https://github.com/fossar/composition-c4) inspired by napalm and the presentation but ideally, I would also link to slides for better navigation.

**Comment by nmattia** [comment]
Took some time to find them, but I do! Thanks for your kind words!

[Overview of Language Support Nixcon 19.pdf](https://github.com/nmattia/nmattia.com/files/6577254/Overview.of.Language.Support.Nixcon.19.pdf)
