### ISSUE TITLE
Add a service worker / PWA support

### ISSUE THREAD

**Issue by peterpeterparker** [nmattia/nmattia.com#8]
If I'm not wrong, your website/blogs isn't shipped with any service worker in order to allows it offline support (would be cool specially for the blog and would also even improve the loading time for returning users)

Roughly, add a `manifest.json` (https://developers.google.com/web/fundamentals/web-app-manifest/) and maybe use `workbox` for the service worker (https://workboxjs.org)

**Comment by nmattia** [comment]
Manifest was added. Service worker is too much for me to look into right now. Thanks for the tip!
