### ISSUE TITLE
Improve accessibility

### ISSUE THREAD

**Issue by peterpeterparker** [nmattia/nmattia.com#9]
To get a dope lighthouse score, the accessibility seems to need some improvements

<img width="1230" alt="capture d ecran 2019-01-22 a 11 57 04" src="https://user-images.githubusercontent.com/16886711/51531170-12dfb580-1e3d-11e9-933c-7fead43718ce.png">

**Comment by nmattia** [comment]
<img width="694" alt="Screenshot 2023-02-19 at 22 32 17" src="https://user-images.githubusercontent.com/6930756/219976470-6dde387a-3a6a-4dd8-8cc8-603c6e1d462e.png">
